### PR TITLE
Addressing navbar fix for issue #4

### PR DESCRIPTION
**Pull request by daniel-moderiano**
Adjusted navbar background color to white to avoid content overlap. 

Closes [#4](https://github.com/keploy/student-program/issues/4)

### CODE REVIEW

**Review by Nishant2907 — APPROVED** [review]
Reviewed

**Review by Nishant2907 — APPROVED** [review]
Reviewed

**Comment by Nishant2907** [comment]
Reviewed and Merged

**Comment by nehagup** [comment]
Thanks @daniel-moderiano 👏

**Pull request merged**
